"""changed activity metaata to activty log a string

Revision ID: 5e920a933048
Revises: d65da67738ff
Create Date: 2026-04-29 16:44:28.587821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e920a933048'
down_revision: Union[str, None] = 'd65da67738ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_activity', sa.Column('activity_log', sa.String(), nullable=True))
    op.drop_column('room_activity', 'activity_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_activity', sa.Column('activity_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('room_activity', 'activity_log')
    # ### end Alembic commands ###