"""drop messages table slim room_metadata room_summaries

Revision ID: 91031ab7de68
Revises: 83432b5c6487
Create Date: 2026-05-01 02:29:58.038206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91031ab7de68'
down_revision: Union[str, None] = '93ecabb237a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_column('room_metadata', 'last_summary_tokens')
    op.drop_column('room_metadata', 'total_tokens')
    op.drop_column('room_metadata', 'last_summarized_message_id')
    op.drop_column('room_summaries', 'to_message_id')
    op.drop_column('room_summaries', 'from_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_summaries', sa.Column('from_message_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('room_summaries', sa.Column('to_message_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('room_metadata', sa.Column('last_summarized_message_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('room_metadata', sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('room_metadata', sa.Column('last_summary_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('messages_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    # ### end Alembic commands ###