"""move invite_version to room_metadata and remove agenda

Revision ID: 93ecabb237a8
Revises: 83432b5c6487
Create Date: 2026-05-01 00:24:06.580232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ecabb237a8'
down_revision: Union[str, None] = '83432b5c6487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_room_member_user', 'room_members', ['room_id', 'user_id'])
    op.add_column('room_metadata', sa.Column('invite_version', sa.Integer(), nullable=False, server_default='1'))
    op.drop_column('rooms', 'invite_version')
    op.drop_column('rooms', 'agenda')
    op.drop_column('rooms', 'custom_instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('custom_instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('agenda', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('invite_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('room_metadata', 'invite_version')
    op.drop_constraint('uix_room_member_user', 'room_members', type_='unique')
    # ### end Alembic commands ###