"""Add unique constraint on owner_id and name

Revision ID: 968204b7ff3e
Revises: f43e919e1c7c
Create Date: 2026-04-29 15:30:21.547481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968204b7ff3e'
down_revision: Union[str, None] = 'f43e919e1c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_owner_room', 'rooms', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_owner_room', 'rooms', type_='unique')
    # ### end Alembic commands ###