"""created new table to maintain activities

Revision ID: d65da67738ff
Revises: 968204b7ff3e
Create Date: 2026-04-29 16:30:45.961505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65da67738ff'
down_revision: Union[str, None] = '968204b7ff3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_activity', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('room_activity', sa.Column('activity_type', sa.String(), nullable=False))
    op.add_column('room_activity', sa.Column('activity_metadata', sa.JSON(), nullable=True))
    op.drop_column('room_activity', 'acitvity_log')
    op.add_column('room_members', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('room_members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('room_members', 'tool')
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'updated_at')
    op.add_column('room_members', sa.Column('tool', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('room_members', 'updated_at')
    op.drop_column('room_members', 'created_at')
    op.add_column('room_activity', sa.Column('acitvity_log', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('room_activity', 'activity_metadata')
    op.drop_column('room_activity', 'activity_type')
    op.drop_column('room_activity', 'user_id')
    # ### end Alembic commands ###