# tools/messaging/router.py
from typing import Optional
from fastmcp import FastMCP, Context
from config.logger import get_logger

from tools.messaging.message import Messaging

logger = get_logger(__name__)

messaging_router = FastMCP("messaging")


@messaging_router.tool()
async def push_message(user_content: str, assistant_content: str, ctx: Context) -> str:
    """
    ALWAYS call this after EVERY assistant response to persist the conversation turn.
    Pushes the user message and assistant response as a pair to the active room.
    Room is resolved automatically from .backroom.json in cwd — no room_id needed.

    INPUT:
    - user_content (str): the user's message text
    - assistant_content (str): the assistant's response text

    OUTPUT (normal):
        '{"status": "ok"}'

    OUTPUT (summary threshold exceeded):
        '{
            "status": "summary_needed",
            "last_summarized_message_id": "<uuid or null>",
            "unsummarized_message_count": <int>
        }'

    NEVER call this if .backroom.json does not exist — call join_room first.
    NEVER call this with empty user_content or assistant_content.
    """
    messaging = Messaging(ctx)
    return await messaging.push_message(user_content, assistant_content)


@messaging_router.tool()
async def pull_messages(
    ctx: Context,
    limit: int = 20,
    offset: int = 0,
    after_id: Optional[str] = None,
) -> str:
    """
    ALWAYS call this at session start to load recent conversation history from the active room.
    Room is resolved automatically from .backroom.json in cwd.

    INPUT:
    - limit (int, default 20): number of messages to return
    - offset (int, default 0): number of messages to skip (for pagination, only used when after_id is not set)
    - after_id (Optional[str], default None): if provided, returns all messages after this message_id
      in chronological order — used when generating a summary to fetch unsummarized messages

    OUTPUT:
    '{
        "messages": [{ "id": str, "message_type": str, "content": str, "created_at": str }],
        "total_messages": int,
        "has_more": bool
    }'

    NEVER call this if .backroom.json does not exist — call join_room first.
    """
    messaging = Messaging(ctx)
    return await messaging.pull_messages(limit=limit, offset=offset, after_id=after_id)


@messaging_router.tool()
async def submit_summary(
    content: str,
    from_message_id: str,
    to_message_id: str,
    ctx: Context,
) -> str:
    """
    ALWAYS call this after generating a summary to persist it and reset the token accumulation counter.
    Inserts a new summary row and snapshots total_tokens into last_summary_tokens so that
    push_message stops returning summary_needed until the next threshold is reached.

    INPUT:
    - content (str): the summary text generated by the agent — see SUMMARY FORMAT below
    - from_message_id (str): UUID of the first message included in this summary
    - to_message_id (str): UUID of the last message included in this summary

    OUTPUT (success): '{"status": "ok"}'
    OUTPUT (validation fail): '{"status": "error", "message": "FAILED: ..."}'

    ───────────────────────────────────────────
    SUMMARY FORMAT (strict — follow exactly)
    ───────────────────────────────────────────

    ## Problem Statement
    What problem or goal was being worked on. One short paragraph.
    Be specific — not "we worked on the app" but "we were trying to fix the
    auth token expiry bug that caused users to be logged out mid-session."

    ## What Was Tried (including failures)
    A list of approaches attempted, including ones that failed and why.
    Failures are critical context — do not omit them.
    Format: "Tried X → result / why it failed"
    Example:
    - Tried increasing JWT expiry to 7d → didn't work, the issue was refresh token not being rotated
    - Tried adding a token refresh interceptor → partially worked but caused race conditions on parallel requests

    ## Decisions Made
    A list of final decisions reached, with the reasoning behind each.
    Format: "Decided X because Y"
    Example:
    - Decided to use sliding session tokens because they handle parallel requests cleanly
    - Decided against Redis session store for now because it adds infra complexity before we've validated the fix

    ## Current State
    Where things stand right now — what is done, what is in progress, what is blocked.
    Be precise about stopping point so the next agent can resume without asking.
    Example: "Auth interceptor is implemented and tested locally. PR is open.
    Blocked on: staging env not reflecting latest build."

    ## Open Questions
    Unresolved questions or decisions that were deferred.
    Example:
    - Should we invalidate all existing tokens on deploy or let them expire naturally?
    - Token expiry duration not finalized — currently 24h, may need to be configurable per user tier

    ## Key References
    Any file names, function names, endpoints, or external links that are essential
    context for whoever picks this up next. Keep it short and specific.
    Example:
    - auth/middleware/tokenRefresh.ts — interceptor lives here
    - /api/auth/refresh — the endpoint being modified
    - PR #142 — open, needs review

    ───────────────────────────────────────────

    Typical flow:
    1. push_message returns status:summary_needed with last_summarized_message_id
    2. Call pull_messages(after_id=last_summarized_message_id) to get unsummarized messages
    3. Read ALL returned messages carefully before writing anything
    4. Generate summary strictly following the format above
    5. Call submit_summary(content, from_message_id, to_message_id)

    NEVER skip sections — if nothing applies to a section, write "None" explicitly.
    NEVER summarize vaguely — a future agent must be able to resume work from this summary alone.
    NEVER call this without first pulling and reading the unsummarized messages.
    NEVER call this if .backroom.json does not exist — call join_room first.
    """
    messaging = Messaging(ctx)
    return await messaging.submit_summary(content, from_message_id, to_message_id)
